name: CI

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 9
                  run_install: false

            - name: Use Node.js v18
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm lint

            - name: Setup files & build
              if: success() || failure()
              run: pnpm setup-files && pnpm build
